    FROM ubuntu:latest

    RUN apt-get update && \
        apt-get install -y apache2 && \
        apt-get clean && \
        rm -rf /var/lib/apt/lists/*
    COPY ./public-html/ /var/www/html/
    EXPOSE 80

    CMD ["apache2ctl", "-D", "FOREGROUND"]

